### PR TITLE
Moving kubernetes related code to relevant repo

### PR DESCRIPTION
**Pull request by nimrodshn**
Moving kubernetes related code to relevant repo.
Kubernetes PR: https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/26
cc: @cben @simon3z

### CODE REVIEW

**Comment by cben** [comment]
Let's also move kubeclient dependency from manageiq-gems-pending.gemspec to our repo.

**Comment by chessbyte** [comment]
Marking as WIP until ManageIQ/manageiq-providers-kubernetes#26 is merged

**Comment by moolitayer** [comment]
@nimrodshn please move out of wip, https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/26 is merged

**Comment by nimrodshn** [comment]
@chessbyte  ManageIQ/manageiq-providers-kubernetes#26 is merged.

**Pull request merged**
