### PR TITLE
Remove miq-deep.rb and specs

### PR DESCRIPTION
**Pull request by djberg96**
These methods and specs were integrated into the more_core_extensions project.

https://github.com/ManageIQ/more_core_extensions/pull/91

### CODE REVIEW

**Comment by Fryguy** [comment]
Can't be merged until more core is released and the reference to it is updated.  I'd expect the update in this PR or an accompanying PR to core (unless it's already been updated?)

**Comment by djberg96** [comment]
@Fryguy Was updated here: https://github.com/ManageIQ/manageiq-gems-pending/pull/486

**Comment by Fryguy** [comment]
Please search the org for miq-deep

**Comment by djberg96** [comment]
@Fryguy Ok, found one outside of gems-pending: https://github.com/ManageIQ/manageiq/pull/20422

**Comment by djberg96** [comment]
@Fryguy Should be clear now with https://github.com/ManageIQ/manageiq/pull/20422 merged.

**Pull request merged**
