### PR TITLE
Add Openstack Panko Events support

### PR DESCRIPTION
**Pull request by aufi**
Openstack Panko service is about to take over Events login from Ceilometer.
Adding support for Panko service with fallback to Ceilometer for Events capture.
Panko API is identical to Events-related Ceilometer part of API.

It should be possible select Events service also manually in settings.

Depends on fog-openstack PR [1] merge and new version published and [2].

Links
--------
 - https://bugzilla.redhat.com/show_bug.cgi?id=1432884
 - https://github.com/fog/fog-openstack/pull/269 MERGED and released (fog support)
 - https://github.com/ManageIQ/manageiq/pull/13985 MERGED (settings.yml option)

### CODE REVIEW

**Comment by aufi** [comment]
https://github.com/fog/fog-openstack/pull/269 was merged, waiting for its release to update gemspec with new fog-openstack version.

**Comment by aufi** [comment]
Required PRs were merged, updating this PR and removing WIP label.

@miq-bot rm_label wip

**Comment by aufi** [comment]
@blomquisg @Ladas Hi, may I ask for review?

**Comment by aufi** [comment]
@miq-bot add_label enhancement

**Comment by Ladas** [comment]
looks great :+1:

**Comment by tzumainn** [comment]
@miq-bot add_label euwe/yes

**Comment by aufi** [comment]
Required by https://bugzilla.redhat.com/show_bug.cgi?id=1436340
@miq-bot add_label blocker

**Comment by simaishi** [comment]
@aufi There are a couple of conflicts backporting this to Euwe. Can you create an Euwe PR for this?

**Comment by aufi** [comment]
@simaishi Sure, euwe backport: https://github.com/ManageIQ/manageiq/pull/14557

**Comment by simaishi** [comment]
Backported to Euwe via https://github.com/ManageIQ/manageiq/pull/14557

**Pull request merged**
