### PR TITLE
[FINE] Remove files that do not seem to be used

### PR DESCRIPTION
**Pull request by borod108**
This files depend on the ovirt-gem and seem not be used so it would be nice to remove them.

### CODE REVIEW

**Comment by chessbyte** [comment]
@borod108 is there an upstream/master PR that this is derived from?

**Comment by chessbyte** [comment]
@borod108 bump

**Comment by chessbyte** [comment]
@borod108 bump

**Comment by borod108** [comment]
This is not relevant anymore.

**Pull request closed without merging**
