### PR TITLE
Upgrade fog-openstack to 0.1.19

### PR DESCRIPTION
**Pull request by sseago**
https://bugzilla.redhat.com/show_bug.cgi?id=1390147

This is needed for bz 1390147.

### CODE REVIEW

**Comment by tzumainn** [comment]
@miq-bot add_label euwe/yes
@miq-bot add_label blocker
@miq-bot add_label bug

**Comment by tzumainn** [comment]
:+1: the fog-openstack change looks good to me!

**Comment by simaishi** [comment]
Backported to Euwe via https://github.com/ManageIQ/manageiq/pull/13417

**Comment by sseago** [comment]
@miq-bot add_label darga/yes

**Comment by sseago** [comment]
@miq-bot remoe_label darga/yes

**Comment by sseago** [comment]
@miq-bot remove_label darga/yes

**Comment by simaishi** [comment]
Backported https://github.com/ManageIQ/manageiq/pull/13417 to Darga

```
$ git log -1
commit a6c651f4b7e5cf540af0276dd9571bec8b2f6aac
Author: Satoe Imaishi <simaishi@redhat.com>
Date:   Thu Jan 12 09:42:43 2017 -0500

    Merge pull request #13417 from sseago/tenant-id-quota-set
    
    [EUWE] Upgrade fog-openstack to 0.1.19
    (cherry picked from commit 01d4d851f829c8670d4b2561114ba10ad4dff96b)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1412684
```

**Pull request merged**
