### PR TITLE
Set timezone

### PR DESCRIPTION
**Pull request by aljesusg**
Set time zone option in CLI  realtion with issue #54

### CODE REVIEW

**Comment by aljesusg** [comment]
@miq-bot add_label bug, enhancement, appliance/console
@miq-bot  assign @carbonin

**Comment by aljesusg** [comment]
@miq-bot remove wip, unmergeable

**Comment by aljesusg** [comment]
@miq-bot remove_label wip, unmergeable

**Comment by aljesusg** [comment]
I did the addition @carbonin Thanks.

**Comment by chessbyte** [comment]
@carbonin bump

**Comment by carbonin** [comment]
@aljesusg do you want to finish fixing up the specs here or should we close these?

**Comment by aljesusg** [comment]
I'll finish it and I'll make more features @carbonin asap. Thanks

**Comment by carbonin** [comment]
@aljesusg I think @chessbyte is trying to extract everything possible out of this repo, so he's interested in getting any pending work finished up before he moves some of the larger pieces.

**Comment by aljesusg** [comment]
Ok @carbonin I try to finish it today. I went home yesterday from san francisco and I had not time. Anyway I think that with this features appliance_console_cli will be crazy tool with all params...Is it possible to have any structure with categories like rake tasks?

**Comment by carbonin** [comment]
@aljesusg I think we definitely want to re-think the design of the cli code, but it will probably be better to get the pending features in and then decide on a new design after.

**Pull request closed without merging**
