### PR TITLE
Remove unused dependencies

### PR DESCRIPTION
**Pull request by Fryguy**
Built on #534 

I'm not sure if this is going to break things, because of the way manageiq-gems-pending is required in gems like smartstate.  I'll add back in things if those repos fail.

### CODE REVIEW

**Comment by Fryguy** [comment]
@miq-bot cross-repo-test /all

**Comment by agrare** [comment]
Looks like master is failing on automation_engine also (gems-pending failure on cross-repo is expected now that it has switched to github actions I guess).

**Comment by agrare** [comment]
https://github.com/ManageIQ/manageiq-automation_engine/pull/489 Fixes this, kicking cross-repo tests

**Comment by Fryguy** [comment]
Thanks for the fix @agrare ...I've rekicked that one job

**Review by agrare — APPROVED** [review]
Just gems-pending failing on .travis.yml now

**Pull request merged**
