### PR TITLE
Add ReFS probe mechanism (fail if detected)

### PR DESCRIPTION
**Pull request by movitto**
https://github.com/ManageIQ/manageiq-gems-pending/issues/129

### CODE REVIEW

**Comment by movitto** [comment]
@roliveri  please review

**Comment by jerryk55** [comment]
I thought I remembered this when I saw the email from @chessbyte today.

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit ce442fc8448214447503099ce282f7154798ae71
Author: Richard Oliveri <oliveri.richard.github@gmail.com>
Date:   Mon Apr 24 15:32:23 2017 -0400

    Merge pull request #109 from movitto/refs
    
    Add ReFS probe mechanism (fail if detected)
    (cherry picked from commit 2a5674708aa4d14246c2fbd37848938b4b44653b)
```

**Comment by simaishi** [comment]
@movitto Is there a BZ for this issue?  A BZ is required to backport to z-stream (Euwe/Darga).

**Comment by movitto** [comment]
@simaishi Hey Satoe, no BZ currently existed, though I just went ahead and created one:

https://bugzilla.redhat.com/show_bug.cgi?id=1445541

This issue was derived from the various issues users & clients were reporting, and the need to add preliminary ReFS detection.

**Comment by simaishi** [comment]
Euwe backport (to manageiq repo) details:

```
$ git log -1
commit 7694d09002429de2b8f26449447b3ab1b930c1a1
Author: Richard Oliveri <oliveri.richard.github@gmail.com>
Date:   Mon Apr 24 15:32:23 2017 -0400

    Merge pull request #109 from movitto/refs
    
    Add ReFS probe mechanism (fail if detected)
    (cherry picked from commit 2a5674708aa4d14246c2fbd37848938b4b44653b)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1448530
```

**Pull request merged**
