### PR TITLE
Add Gnocchi metric service to Openstack handle

### PR DESCRIPTION
**Pull request by aufi**
In order to support metrics in OSP10, we need add support methods for
Gnocchi service.

This PR contains backend methods for https://github.com/ManageIQ/manageiq/pull/12396

### CODE REVIEW

**Comment by tzumainn** [comment]
Do you have to update manageiq-gems-pending.gemspec?

s.add_runtime_dependency "fog-openstack",           "=0.1.15"

**Comment by tzumainn** [comment]
Duh, I see it now, sorry!

**Comment by tzumainn** [comment]
:+1: looks good to me!

**Comment by blomquisg** [comment]
Ugh, I was gonna ask why we would have a `metric` *and* a `metering` delegate, but it looks like that's what OpenStack is actually calling the Gnocchi and Ceilometer services, respectively.

**Comment by aufi** [comment]
@blomquisg Yeah, Metric in a new service in Openstack (but was extracted from Metering), for some time we need support both

**Comment by blomquisg** [comment]
@aufi gotcha

**Pull request merged**
