### PR TITLE
Allow IPv4 DNS for IPv6 network

### PR DESCRIPTION
**Pull request by isimluk**
https://bugzilla.redhat.com/show_bug.cgi?id=1448878

People may want to have static IPv6 and static IPv4 and use only IPv4 DNS.

### CODE REVIEW

**Comment by isimluk** [comment]
🐖

**Comment by simaishi** [comment]
@isimluk @gtanzillo should this be `fine/yes` (as per BZ flag)?

**Comment by gtanzillo** [comment]
@simaishi Yes, I just added the label. Thanks.

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 6d84116b28df138de7c19ae08b66a075d80cdb89
Author: Gregg Tanzillo <gtanzill@redhat.com>
Date:   Tue Jun 20 12:03:45 2017 -0400

    Merge pull request #203 from isimluk/rhbz#1448878
    
    Allow IPv4 DNS for IPv6 network
    (cherry picked from commit 938d92a9afdcaa682cd978361d566e8e7d25534c)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1463848
```

**Pull request merged**
