### PR TITLE
Remove dependency on rufus-lru gem

### PR DESCRIPTION
**Pull request by chessbyte**
~~Could not find anything referencing `rufus-lru` nor `Rufus::Lru`~~

Moved dependency to https://github.com/ManageIQ/manageiq-smartstate/pull/7

### CODE REVIEW

**Comment by jerryk55** [comment]
@chessbyte there is a reference in what is now manageiq-smartstate for which I do not see a dependency listed.  I am started to lose my way through the list of dependencies and don't understand why that still works but I assume it may have to do with the dependency you are about to remove.

**Comment by jrafanie** [comment]
LruHash is provided by rufus-lru and we use that in the fleecing (manageiq-smartstate) code.

```
04:44:00 ~/Code/manageiq (master) (2.4.1) - grep -r -E "LruHash|Rufus::Lru" /Users/joerafaniello/.gem/ruby/2.4.1
/Users/joerafaniello/.gem/ruby/2.4.1/gems/manageiq-smartstate-0.1.1/lib/disk/modules/miq_disk_cache.rb:    @block_cache           = LruHash.new(@dInfo.lru_hash_entries)
/Users/joerafaniello/.gem/ruby/2.4.1/gems/manageiq-smartstate-0.1.1/lib/fs/ext3/superblock.rb:      @block_cache = LruHash.new(DEF_BLOCK_CACHE_SIZE)
/Users/joerafaniello/.gem/ruby/2.4.1/gems/manageiq-smartstate-0.1.1/lib/fs/ext3/superblock.rb:      @inode_cache = LruHash.new(DEF_INODE_CACHE_SIZE)
/Users/joerafaniello/.gem/ruby/2.4.1/gems/manageiq-smartstate-0.1.1/lib/fs/ext4/superblock.rb:      @block_cache = LruHash.new(DEF_BLOCK_CACHE_SIZE)
/Users/joerafaniello/.gem/ruby/2.4.1/gems/manageiq-smartstate-0.1.1/lib/fs/ext4/superblock.rb:      @inode_cache = LruHash.new(DEF_INODE_CACHE_SIZE)
/Users/joerafaniello/.gem/ruby/2.4.1/gems/manageiq-smartstate-0.1.1/lib/fs/MiqFS/modules/Ext3.rb:    self.entry_cache = LruHash.new(DEF_CACHE_SIZE)
/Users/joerafaniello/.gem/ruby/2.4.1/gems/manageiq-smartstate-0.1.1/lib/fs/MiqFS/modules/Ext3.rb:    self.dir_cache   = LruHash.new(DEF_CACHE_SIZE)
/Users/joerafaniello/.gem/ruby/2.4.1/gems/manageiq-smartstate-0.1.1/lib/fs/MiqFS/modules/Ext4.rb:    self.entry_cache = LruHash.new(DEF_CACHE_SIZE)
/Users/joerafaniello/.gem/ruby/2.4.1/gems/manageiq-smartstate-0.1.1/lib/fs/MiqFS/modules/Ext4.rb:    self.dir_cache   = LruHash.new(DEF_CACHE_SIZE)
/Users/joerafaniello/.gem/ruby/2.4.1/gems/manageiq-smartstate-0.1.1/lib/fs/MiqFS/modules/Fat32.rb:    self.dir_cache = LruHash.new(DEF_CACHE_SIZE)
/Users/joerafaniello/.gem/ruby/2.4.1/gems/manageiq-smartstate-0.1.1/lib/fs/MiqFS/modules/Iso9660.rb:    self.dir_cache = LruHash.new(DEF_CACHE_SIZE)
/Users/joerafaniello/.gem/ruby/2.4.1/gems/manageiq-smartstate-0.1.1/lib/fs/MiqFS/modules/NTFS.rb:    self.index_cache = LruHash.new(DEF_CACHE_SIZE)
/Users/joerafaniello/.gem/ruby/2.4.1/gems/manageiq-smartstate-0.1.1/lib/fs/MiqFS/modules/ReiserFS.rb:    self.entry_cache = LruHash.new(DEF_CACHE_SIZE)
/Users/joerafaniello/.gem/ruby/2.4.1/gems/manageiq-smartstate-0.1.1/lib/fs/MiqFS/modules/ReiserFS.rb:    self.dir_cache   = LruHash.new(DEF_CACHE_SIZE)
/Users/joerafaniello/.gem/ruby/2.4.1/gems/manageiq-smartstate-0.1.1/lib/fs/MiqFS/modules/XFS.rb:    self.entry_cache = LruHash.new(DEF_CACHE_SIZE)
/Users/joerafaniello/.gem/ruby/2.4.1/gems/manageiq-smartstate-0.1.1/lib/fs/MiqFS/modules/XFS.rb:    self.dir_cache   = LruHash.new(DEF_CACHE_SIZE)
/Users/joerafaniello/.gem/ruby/2.4.1/gems/manageiq-smartstate-0.1.1/lib/fs/ntfs/boot_sect.rb:      @mfts        = LruHash.new(NTFS::DEF_CACHE_SIZE)
/Users/joerafaniello/.gem/ruby/2.4.1/gems/manageiq-smartstate-0.1.1/lib/fs/ReiserFS/superblock.rb:      @leaf_nodes   = LruHash.new(DEF_LEAF_NODE_CACHE_SIZE)
/Users/joerafaniello/.gem/ruby/2.4.1/gems/manageiq-smartstate-0.1.1/lib/fs/xfs/superblock.rb:      @block_cache            = LruHash.new(DEF_BLOCK_CACHE_SIZE)
/Users/joerafaniello/.gem/ruby/2.4.1/gems/manageiq-smartstate-0.1.1/lib/fs/xfs/superblock.rb:      @cluster_cache          = LruHash.new(DEF_CLUSTER_CACHE_SIZE)
/Users/joerafaniello/.gem/ruby/2.4.1/gems/manageiq-smartstate-0.1.1/lib/fs/xfs/superblock.rb:      @inode_cache            = LruHash.new(DEF_INODE_CACHE_SIZE)
/Users/joerafaniello/.gem/ruby/2.4.1/gems/manageiq-smartstate-0.1.1/lib/fs/xfs/superblock.rb:      @allocation_group_cache = LruHash.new(DEF_AG_CACHE_SIZE)
```

You should move this dependency to the smartstate gemspec as a runtime_dependency...

**Comment by jrafanie** [comment]
Once that's merged, we can merge this one

**Comment by chessbyte** [comment]
Thanks @jerryk55 @jrafanie -- see https://github.com/ManageIQ/manageiq-smartstate/pull/7

**Comment by chessbyte** [comment]
Removing `wip` label now that ManageIQ/manageiq-smartstate#7 is merged

**Pull request merged**
