### PR TITLE
bump hawkular client version

### PR DESCRIPTION
**Pull request by alongoldboim**
This Gem bump is needed for strings metric support for Hawkular.

### CODE REVIEW

**Comment by alongoldboim** [comment]
@blomquisg Please have a look :)

**Comment by bdunne** [comment]
@alongoldboim Is this related to a bug or new features?

**Comment by Fryguy** [comment]
Please rebase now that the repo has Travis support.

**Comment by alongoldboim** [comment]
@bdunne rebased, added desc.

**Comment by simon3z** [comment]
cc @pilhuhn @lucasponce

**Comment by pilhuhn** [comment]
The upgrade is fine with me - I just did not want to introduce it for Euwe, as Middleware does not
need the new features.

**Pull request merged**
