### PR TITLE
Remove old and unused ServiceNowWebService code

### PR DESCRIPTION
**Pull request by chessbyte**

### CODE REVIEW

**Comment by gmcculloug** [comment]
This PR requires cleanup of ServiceNow references in https://github.com/ManageIQ/manageiq-automation_engine.

Found references in three places
https://github.com/ManageIQ/manageiq-automation_engine/blob/master/lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_builtin_method.rb#L45
https://github.com/ManageIQ/manageiq-automation_engine/blob/master/lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service_methods.rb#L100
https://github.com/ManageIQ/manageiq-automation_engine/blob/master/spec/data/method_service_now/SPEC_DOMAIN/Factory/ServiceNow.class/eccq_insert.yaml

**Comment by chessbyte** [comment]
Marking as WIP because of @gmcculloug findings in https://github.com/ManageIQ/manageiq-gems-pending/pull/167#issuecomment-302743664

@mkanoor Can you work with @gmcculloug to resolve/remove the callers?

**Comment by Fryguy** [comment]
😖  I checked that repo for Rcu and Vco, but not Eccq

**Comment by gmcculloug** [comment]
@chessbyte https://github.com/ManageIQ/manageiq-automation_engine/pull/26 is merged.

**Pull request merged**
