### PR TITLE
bump kubeclient ~> 2.4.0

### PR DESCRIPTION
**Pull request by cben**
Needed for ManageIQ/manageiq-providers-kubernetes#10 to control timeout.
https://bugzilla.redhat.com/show_bug.cgi?id=1440950

cc @moolitayer @simonz @agrare

### CODE REVIEW

**Comment by agrare** [comment]
@cben is there a reason you want to lock it to `=2.4.0` and not `~>2.4.0`?

**Comment by cben** [comment]
Dunno, it was `=2.3.0` :-)  @simon3z what do you prefer?
Also, what are your backport/hotfix plans?  Will you release kubeclient 2.3.1 or use 2.4.0?

**Comment by simon3z** [comment]
> Dunno, it was =2.3.0 :-) @simon3z what do you prefer?
> Also, what are your backport/hotfix plans? Will you release kubeclient 2.3.1 or use 2.4.0?

@cben @agrare I don't plan to do hotfixes, but I guess `~>2.4.0` is safe/good anyway.

**Comment by agrare** [comment]
Thanks @cben !

**Comment by cben** [comment]
@miq-bot add-label euwe/yes, fine/yes

**Comment by cben** [comment]
FYI kubeclient 2.4.0 also brings much newer `http` gem (which is used for watches).
I've tested it a little bit, but are we confident backporting it?
Well, z-streams do go through QE...

**Comment by agrare** [comment]
@cben could we use `kubeclient-2.3.1` (https://github.com/abonas/kubeclient/pull/246) and update the euwe gemfile to be `~>2.3.0`?

**Comment by cben** [comment]
Sure, depends if @simon3z decides to make a 2.3.1 release.

**Comment by simon3z** [comment]
> @cben could we use kubeclient-2.3.1 (abonas/kubeclient#246) and update the euwe gemfile to be ~>2.3.0?

@agrare why? 2.4 is backward compatible and the only changes are the timeout addition.

**Comment by agrare** [comment]
@simon3z because @cben didn't sound confident​ backporting 2.4.0

**Comment by cben** [comment]
See above.  I don't have anything particular against the newer http gem,
beyond general principle that it's not really a necessary change for us.
Your call.

**Comment by simon3z** [comment]
> @simon3z because @cben didn't sound confident​ backporting 2.4.0

@agrare @cben `2.4.0` was built only with the addition of the timeout. It's all in the git history you can check:

```
$ git log --no-merges --oneline v2.3.0..v2.4.0
6f12480 Bump version to 2.4.0
539591f Add timeouts option
991871e ParameterLists rubocop: don't penalize keyword args
cecf873 Test both rest-client 1.8 and latest
```

**Comment by cben** [comment]
aaaah cool :+1:.   Now the `v2.x` branch name makes sense.  For some reason I always assumed master will become 2.4 and was blind to contrary evidence.

**Comment by agrare** [comment]
:+1: I'm good with backporting it then

**Comment by simaishi** [comment]
Marking as `euwe/conflict` as this needs to go to `gems/pending/Gemfile` in manageiq repo. @cben please remove the `conflict` label when you have Euwe PR. Thanks!

**Comment by simaishi** [comment]
Backported to Euwe via https://github.com/ManageIQ/manageiq/pull/15188

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 090bb77f454bdb351f34e3f365eadb6ec368b1fe
Author: Adam Grare <agrare@redhat.com>
Date:   Wed May 10 09:07:44 2017 -0400

    Merge pull request #156 from cben/kubeclient-timeout
    
    bump kubeclient ~> 2.4.0
    (cherry picked from commit 0aeea3dee8d470eca4f0553d79bf8cb35d66e344)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1459929
```

**Pull request merged**
