### PR TITLE
Extract SmartState Analysis to separate repo

### PR DESCRIPTION
**Pull request by chessbyte**
Extracting to new repo named `manageiq-smartstate`.  See https://github.com/ManageIQ/manageiq-smartstate

Should be merged after https://github.com/ManageIQ/manageiq/pull/15241

### CODE REVIEW

**Comment by bdunne** [comment]
:+1: Cool!!

**Comment by jerryk55** [comment]
@chessbyte I would add the following:
Scvmm/* (miq_hyperv_disk.rb, miq_scvmm_vm_ssa_info.rb, mix_scvmm_parse_powershell.rb)
util/miq_winrm.rb (although we may want to make this a separate gem and have the SCVMM refresh code use it as well)

**Comment by chessbyte** [comment]
@jerryk55 Extracted Scvmm dirs

**Comment by Fryguy** [comment]
I think https://github.com/chessbyte/manageiq-gems-pending/tree/51036ddf88f832edf9e582a31fd032c7e958544e/lib/gems/pending/MiqContainerGroup has to come over also.  @simon3z ?

**Comment by simon3z** [comment]
> I think https://github.com/chessbyte/manageiq-gems-pending/tree/51036ddf88f832edf9e582a31fd032c7e958544e/lib/gems/pending/MiqContainerGroup has to come over also. @simon3z ?

@Fryguy yes it's part of SSA for containers. cc @enoodle @cben

**Comment by chessbyte** [comment]
@Fryguy @simon3z Included `MiqContainerGroup`

**Comment by Fryguy** [comment]
You may also need the .gitignores: https://github.com/ManageIQ/manageiq-gems-pending/blob/master/lib/gems/pending/.gitignore#L7-L8

You will also need to copy the .rspec_ci file in the new repo or it will fail on travis (and if .rspec file doesn't match, copy the one from here as well).

**Comment by chessbyte** [comment]
@Fryguy thanks for the feedback.  Implemented it, where appropriate, in both repos.

**Pull request merged**
