### PR TITLE
Move VixDiskLib under VMwareWebService

### PR DESCRIPTION
**Pull request by agrare**
There are dependencies between `VMwareWebService` and `VixDiskLib` so move `VixDiskLib` under `VMwareWebService` so they can be extracted together

Related: https://github.com/ManageIQ/manageiq/pull/15204

### CODE REVIEW

**Comment by agrare** [comment]
cc @jerryk55 
I tested calling `vdlConnection` from a `MiqVim` connection and it loaded okay but I could use help testing  it with a real disk.

**Comment by jerryk55** [comment]
@agrare my appliance is currently configured with the manageiq-smartstate repo changes - let me see what I can do to try to test this...

**Comment by agrare** [comment]
Successfully scanned a VMDK and everything looks good :)

**Comment by jerryk55** [comment]
Cool!  Should be good to go!

**Pull request merged**
