### PR TITLE
Extract MiqStats in favor of Math extension in more_core_extensions

### PR DESCRIPTION
**Pull request by Fryguy**
Depends on https://github.com/ManageIQ/more_core_extensions/pull/50 and subsequent release.

### CODE REVIEW

**Comment by Fryguy** [comment]
@bdunne Please review...My plan is to replace callers after this change in a separate PR.

**Comment by Fryguy** [comment]
@gtanzillo @jrafanie This is ready to go.

**Comment by jrafanie** [comment]
Do the callers' tests pass with this branch?  I'm all for deletions but hopefully it still works 😉

**Comment by Fryguy** [comment]
All of the tests were moved to the more_core_extensions thing and they all pass.  Alternately, I can straight remove it via https://github.com/ManageIQ/manageiq/pull/18599, and then change this PR to a complete removal PR.

**Pull request merged**
