### PR TITLE
hawkular-client isn't referenced anywhere in manageiq-gems-pending

### PR DESCRIPTION
**Pull request by bdunne**
Depends on https://github.com/ManageIQ/manageiq-providers-hawkular/pull/15 and https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/13

### CODE REVIEW

**Comment by bdunne** [comment]
Removing [WIP] since the dependency is already merged to manageiq-providers-kubernetes, so the gem will be included from that plugin even if it is not yet merged to manageiq-providers-hawkular.

**Comment by Fryguy** [comment]
@bdunne What about https://github.com/ManageIQ/manageiq-providers-openshift ?

**Comment by bdunne** [comment]
@Fryguy The only reference I see is:
```
app/models/manageiq/providers/openshift/container_manager/refresher.rb:15:        hawk = ManageIQ::Providers::Kubernetes::ContainerManager::MetricsCapture::HawkularClient.new(ems, '_ops')
```
So, I think this gem should depend on `manageiq-providers-kubernetes`

**Comment by Fryguy** [comment]
That gets tricky though because of the git references, right?

**Comment by bdunne** [comment]
Yep.  Maybe we need an issue?

**Comment by Fryguy** [comment]
yeah, I think an issue is good.

**Comment by bdunne** [comment]
https://github.com/ManageIQ/manageiq-providers-openshift/issues/14

**Pull request merged**
