### PR TITLE
[FINE] Prevent iteration over all tenants when picking default tenant

### PR DESCRIPTION
**Pull request by tzumainn**
Backport of https://github.com/ManageIQ/manageiq-providers-openstack/pull/62

https://bugzilla.redhat.com/show_bug.cgi?id=1470800

### CODE REVIEW

**Comment by simaishi** [comment]
@blomquisg this is a blocker for the next build - please review or assign someone to review. Thanks!

**Comment by simaishi** [comment]
@aufi @Ladas can you review please?

**Comment by aufi** [comment]
The change looks good to me, but it might be needed update VCR tests in main repo fine branch after merging this.

**Comment by simaishi** [comment]
Travis is failing in the `managiq` repo now: https://travis-ci.org/ManageIQ/manageiq/jobs/255268538

@tzumainn as @aufi mentioned, VCR needs to be updated?

**Comment by tzumainn** [comment]
I'll take a look!

**Comment by tzumainn** [comment]
This should hopefully be fixed by https://github.com/ManageIQ/manageiq/pull/15622 - I'll keep an eye out.

**Pull request merged**
