### PR TITLE
Specify rhel7 as the scap security guide platform

### PR DESCRIPTION
**Pull request by carbonin**
Requires https://github.com/ManageIQ/linux_admin/pull/191 and https://github.com/ManageIQ/linux_admin/pull/192

https://bugzilla.redhat.com/show_bug.cgi?id=1493193

### CODE REVIEW

**Comment by carbonin** [comment]
This also will need a linux_admin version bump to pick up the referenced PRs.

**Comment by carbonin** [comment]
:tada: Ping @bdunne This will bring in the new linux_admin version

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 513e4d07dfcf0aec782613905b8da872689c4ae5
Author: Brandon Dunne <brandondunne@hotmail.com>
Date:   Tue Oct 3 13:34:22 2017 -0400

    Merge pull request #275 from carbonin/specify_platform_for_scap
    
    Specify rhel7 as the scap security guide platform
    (cherry picked from commit 2f0d09ff0147bf1bd230e87ac799e300c3e30067)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1498230
```

**Comment by simaishi** [comment]
Euwe backport details:

```
$ git log -1
commit e303bdb8345b8c47f87651f359bcee4a6ab5468f
Author: Brandon Dunne <brandondunne@hotmail.com>
Date:   Tue Oct 3 13:34:22 2017 -0400

    Merge pull request #275 from carbonin/specify_platform_for_scap
    
    Specify rhel7 as the scap security guide platform
    (cherry picked from commit 2f0d09ff0147bf1bd230e87ac799e300c3e30067)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1498232
```

**Pull request merged**
