### PR TITLE
Bump Kubeclient version to 2.3.0

### PR DESCRIPTION
**Pull request by zakiva**
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1387614
@simon3z @moolitayer

### CODE REVIEW

**Comment by simon3z** [comment]
LGTM :+1:

**Comment by simon3z** [comment]
@zakiva @moolitayer did you test this extensively? Please explicitly mention what you tested (OpenShift versions that you tested 3.1/3.2/3.3/3.4? What flows? We collect some information also during SmartState Analysis did you check that?).
We can't afford regressions here.

**Comment by simon3z** [comment]
Regressions questions are being handled in https://github.com/ManageIQ/manageiq/pull/12978

This one is OK, LGTM :+1:

Ready for merge @chessbyte @blomquisg @gtanzillo

**Comment by chessbyte** [comment]
Backported to Euwe via https://github.com/ManageIQ/manageiq/pull/12978

**Pull request merged**
