### PR TITLE
[Changelog] Rollup of Ivanchuk releases

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot add_label ivanchuk/yes

**Comment by JPrause** [comment]
@agrare can you review/merge as time permits.

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 652327d817f6b388aaba12858d4d6ed29da2858f
Author: Satoe Imaishi <simaishi@redhat.com>
Date:   Tue Sep 10 12:24:32 2019 -0400

    Merge pull request #448 from JPrause/ivanchukGA_cl
    
    [Changelog] Rollup of Ivanchuk releases
    
    (cherry picked from commit a7e12fbcdfb0c17b033dbbc39ca9c0de778e7d75)
```

**Pull request merged**
