### PR TITLE
remove to_miq_a

### PR DESCRIPTION
**Pull request by d-m-u**
https://github.com/ManageIQ/manageiq/pull/20433 and https://github.com/ManageIQ/manageiq-smartstate/pull/136  removed the callers so we should be able to remove to_miq_a and the relevant tests now

### CODE REVIEW

**Comment by chessbyte** [comment]
Don’t we need to first release a new SmartState gem and require it somewhere, so that we are, in fact, no longer using `to_miq_a`?

**Comment by d-m-u** [comment]
Yeah, sorry, just hadn't gotten around to opening that PR yet.

**Comment by Fryguy** [comment]
I assume we've bumped to the expected version of smartstate.  Is this ready to go now?

**Comment by d-m-u** [comment]
nope, sorry, we haven't bumped smartstate yet, this isn't ready

**Comment by d-m-u** [comment]
hey @Fryguy if you give me a review/merge on https://github.com/ManageIQ/manageiq-smartstate/pull/137 then we can bump that version and merge these, maybe?

**Comment by d-m-u** [comment]
still needs a smartstate release

**Comment by d-m-u** [comment]
looks like this is good to go: https://github.com/ManageIQ/manageiq-smartstate/commit/1ac422b09c89f90e70529edd86c93213437903d3

**Pull request merged**
