### PR TITLE
[WIP] Extract appliance_console to separate repo

### PR DESCRIPTION
**Pull request by chessbyte**
Extracted repo in https://github.com/chessbyte/manageiq-appliance_console

### CODE REVIEW

**Comment by bdunne** [comment]
@chessbyte Will you be adding all of the usual gem parts (gemspec, rspec, etc.) to that repo?  The appliance_console_cli should also live in `bin/`

**Comment by carbonin** [comment]
When this gem is fully extracted and released, the dependency should be listed in the file added in https://github.com/ManageIQ/manageiq-appliance/pull/125

**Comment by chessbyte** [comment]
@carbonin @bdunne @Fryguy please see extracted repo in https://github.com/chessbyte/manageiq-appliance_console  

I think we can use this PR to comment on it.

**Comment by chessbyte** [comment]
@bdunne @carbonin @Fryguy So what should I do with dir https://github.com/chessbyte/manageiq-appliance_console/tree/master/lib/appliance_console ?  Should I add a manageiq dir in between `lib` and `appliance_console` dirs to conform to the repo/gem name?

**Comment by Fryguy** [comment]
I personally would add the dir in between with a second pass on git filter-branch.  Then a follow up commit to just tack in the ManageIQ namespace (you probably don't need it at every caller, just at the definition).

**Comment by chessbyte** [comment]
@bdunne I know we discussed you taking over this PR.  Please let me know if I need to give you any permissions to anything.

**Comment by chessbyte** [comment]
Closing in favor of https://github.com/ManageIQ/manageiq-gems-pending/pull/292

**Pull request closed without merging**
